[package]
edition = "2018"
name = "scout-core"
version = "0.0.1"
description = "Scout"
authors = [ "Auri <me@auri.xyz>" ]

[build-dependencies]
rustc_version = "0.2"

[dependencies]
whoami = "1.1.2"
freedesktop_entry_parser = "1.1.1"
gtk = { version = "0.9.0", features = [ "v3_24" ] }
